CREATE TABLE `module_system`.`user` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`login` VARCHAR( 20 ) NOT NULL ,
`password` VARCHAR( 32 ) NOT NULL ,
`theme` TINYINT UNSIGNED NULL ,
`cookie_solt` INT UNSIGNED NOT NULL ,
`is_confirm` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT '0',
`is_remove` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE = MYISAM ;